#!/bin/bash

function jenkins-dind-docker-build() {

  jenkins-dind-init
  FIRST_OLDPWD="$PWD"
  cd $PROJECT_DIR
  export TIMESTAMP=$(date +%Y%m%d%H%M)
  cd $PROJECT_DIR
  docker build -t $DOCKER_IMAGE .
  cd $FIRST_OLDPWD

}
