sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=emergya/jenkins-dind
    - GIT_URL=git@github.com:Emergya/jenkins-dind.git

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y quilt

script:
  - test -f ~/.baids/baids || curl -sSL https://raw.githubusercontent.com/rcmorano/baids/master/baids | bash -s install
  - test -L ~/.baids/functions.d/jenkins-dind || ln -nfs $PWD/baids ~/.baids/functions.d/jenkins-dind
  - /bin/bash --login -c 'source ~/.baids/baids; set -e; jenkins-dind-docker-build'

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag emergya/jenkins-dind:latest emergya/jenkins-dind:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push emergya/jenkins-dind:latest;
      docker push emergya/jenkins-dind:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      curl -ILk 'https://'"${JENKINS_USER}"':'"${JENKINS_API_TOKEN}"'@jenkins.emergya.com/job/'"${JENKINS_JOB_NAME}"'/buildWithParameters?token='"${JENKINS_JOB_TOKEN}"'&GIT_URL='"${GIT_URL}"'&DOCKER_IMAGE='"${DOCKER_IMAGE}";
    fi

notifications:
  email:
    recipients:
      - emergya-integration-github@emergya.com
    on_success: always
    on_failure: always
